name: "Bug report"
description: "不具合の報告"
title: "Fix: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: 現象
      description: 何が起きているか（AIが再現手順・影響を spec/plan で詰めます）
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 期待する動作
      description: 簡潔に
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: 備考
      description: 関連する Spec/UC/環境などがあれば（空でも可）
